### ISSUE TITLE
Add Makefile target to install the correct version of Hugo

### ISSUE THREAD

**Issue by doeg** [vitessio/website#1005]
It'd be useful to add a little bit of tooling to ensure that a developer's local Hugo install matches the version specified in the [netlify.toml](https://github.com/vitessio/website/blob/4e29cea/netlify.toml#L6) file. Currently, developers need to install + upgrade Hugo locally on their own, as documented in the [README](https://github.com/vitessio/website/blob/31d3b32/README.md).

**Comment by chalin** [comment]
See #1107
