### ISSUE TITLE
Broken redirect

### ISSUE THREAD

**Issue by derekperkins** [vitessio/website#101]
https://vitess.io/docs/user-guides/server-configuration/

**Comment by lucperkins** [comment]
Just out of curiosity, where are you seeing that URL?

The current URL is https://vitess.io/docs/launching/server-configuration, which is also the page that comes up when I Google “Vitess configuration.”

**Comment by derekperkins** [comment]
![image](https://user-images.githubusercontent.com/3588778/49567468-fe764680-f8ea-11e8-896b-6cb3552043db.png)

It started working after you merged that last PR

**Comment by lucperkins** [comment]
Okay, cool. I’ll close this for now but feel free to re-open if necessary.

In the future, you can modify this file to establish any custom redirects:

https://github.com/vitessio/website/blob/master/static/_redirects
