### ISSUE TITLE
Investigate better ways to do presentation display

### ISSUE THREAD

**Issue by skinnylatte** [vitessio/website#105]
Old site had GViewer, which is no longer working well.

I switched the presentations section to ViewerJS, with the files hosted in the `static` directory.

The current dimensions / usage of ViewerJS is not working well on mobile devices.

@lucperkins can you help me look into optimizing the presentations page experience with ViewerJS or other tools?

**Comment by skinnylatte** [comment]
@derekperkins @deepthi I have not heard many complaints about this section yet but I am not happy with how ViewerJS looks and works on mobile.

Any thoughts or ideas?

**Comment by morgo** [comment]
I am going to close this for now. It looks good to me.
