### ISSUE TITLE
Add third column in docs

### ISSUE THREAD

**Issue by derekperkins** [vitessio/website#107]
Nothing urgent, but the third column navigation that exists in the user guides is missing from the vtctl and api reference pages.
https://vitess.io/docs/reference/vtctl/#executefetchasdba

**Comment by lucperkins** [comment]
That’s because the TOC is automatically generated and there are hundreds of headers on those pages, far too many for the TOC to be useful. I’ll see if I can think of a better way.

**Comment by morgo** [comment]
I think this looks good for now. My plan is to work on improving user-guides first, and then I'll take a look at reference.

I would like to add these under a subheading such as "Programs", and then have a structured reference for everything in the `bin` directory:
```
automation_client
automation_server
consul
cover
demo
etcd
goimports
golint
govendor
goyacc
mockgen
mysqlctl
mysqlctld
protoc
query_analyzer
staticcheck
topo2topo
unused
vtaclcheck
vtbackup
vtbench
vtclient
vtcombo
vtctl
vtctlclient
vtctld
vtexplain
vtgate
vtgateclienttest
vtqueryserver
vttablet
vttestserver
vttlstest
vtworker
vtworkerclient
zk
zkctl
zkctld
zksrv.sh
```

We can track this in #331. I am going to close this issue for now.
