### ISSUE TITLE
MySQL compatibility page is outdated

### ISSUE THREAD

**Issue by deepthi** [vitessio/website#1072]
https://vitess.io/docs/14.0/reference/compatibility/mysql-compatibility/

- We link to `unsupported-cases.txt`. However, that file is itself incomplete because it does not include new 8.0 syntax
- DDL section is incorrect. We no longer recommend external schema management. We should recommend our own online DDL and link to that
- Is this still true? ` LEFT JOIN is supported as long as there are not expressions that compare columns on the outer table to the inner table in sharded keyspaces.`
- Ordering is definitely outdated `Vitess supports the ordering for all the columns irrespective of the data type. However it further requests collation specific information (weight_string) from the underlying MySQL instance. This can be avoided for numeric columns which is discussed further in [Advanced VSchema Properties](https://vitess.io/docs/14.0/user-guides/vschema-guide/advanced-vschema/#column-list)`
- Cross-shard Transactions `By default, Vitess does not support transactions that span across shards. While Vitess can support this with the use of [Two-Phase Commit](https://vitess.io/docs/14.0/reference/features/two-phase-commit), it is usually recommended to design the VSchema in such a way that cross-shard modifications are not required.` I believe this is also incorrect. Default mode is `MULTI` not `SINGLE`
- We might want to add a section on JSON / other 8.0 constructs that we now support
- Collations section is out-of-date

**Comment by deepthi** [comment]
@vitessio/query-serving / @shlomi-noach / @vmg

**Comment by shlomi-noach** [comment]
Re: `LEFT JOIN`, cross reference to https://github.com/planetscale/docs.planetscale.com/pull/1483 which documents the same, on PSDB docs. If untrue, then this needs to be removed in both places.

**Comment by shlomi-noach** [comment]
https://github.com/vitessio/website/pull/1082 updates docs for Online DDL

**Comment by harshit-gangal** [comment]
> We might want to add a section on JSON / other 8.0 constructs that we now support

Vitess always supported functions that are passed through, there is nothing new we need to add for json as they are still not handled at vtgate

> Is this still true? LEFT JOIN is supported as long as there are not expressions that compare columns on the outer table to the inner table in sharded keyspaces.

This is not true anymore, Vitess support such queries

I will take a look and update that doc.

**Comment by harshit-gangal** [comment]
PR: https://github.com/vitessio/website/pull/1096

**Comment by harshit-gangal** [comment]
PR is merged.
