### ISSUE TITLE
Update backup/restore docs

### ISSUE THREAD

**Issue by deepthi** [vitessio/website#1089]
https://github.com/vitessio/vitess/pull/10558 added support for more options for compression/decompression.
That needs to be documented.
This is also a good opportunity to review and revise the docs if needed.

**Comment by deepthi** [comment]
cc @rvrangel @rsajwani

**Comment by rvrangel** [comment]
Started a PR (work in progress) for this here https://github.com/vitessio/website/pull/1091

**Comment by deepthi** [comment]
Fixed.
