### ISSUE TITLE
Review and update VReplication migration cutover guide

### ISSUE THREAD

**Issue by deepthi** [vitessio/website#1092]
https://vitess.io/docs/14.0/user-guides/migration/cutover/

Most of the information is still current, but the Performance section refers to what are now very old versions of Vitess. It needs to be either brought up-to-date, or we may be able to remove some content from there regarding versions before 11.0 (currently the earliest supported version)

We may need to change it again when we delete the deprecated v1 commands.

**Comment by mattlord** [comment]
Closing this as this page is being updated as part of https://github.com/vitessio/website/issues/1234
