### ISSUE TITLE
Nav items are not visible on mobile

### ISSUE THREAD

**Issue by thisisobate** [vitessio/website#1156]
<img width="772" alt="Screenshot 2022-10-04 at 10 05 51" src="https://user-images.githubusercontent.com/29557702/193780544-3c15f697-11ba-4ccb-be83-b90b95e2ac35.png">

**Comment by deepthi** [comment]
The only recent change is https://github.com/vitessio/website/pull/1117. Do you think that broke the mobile nav?

**Comment by thisisobate** [comment]
Yeah, I think so

**Comment by thisisobate** [comment]
Would push a fix for this once I get [this](https://github.com/vitessio/website/pull/1119) in
