### ISSUE TITLE
Search does not handle incorrect input appropriately

### ISSUE THREAD

**Issue by thisisobate** [vitessio/website#1157]

**Comment by nate-double-u** [comment]
Follow up to https://github.com/vitessio/website/pull/1119

**Comment by deepthi** [comment]
Agreed. Example:
![Screen Shot 2022-10-05 at 4 46 36 PM](https://user-images.githubusercontent.com/388311/194183733-1f3918bc-43af-4bbd-99bc-aa4e1e872ede.png)
You can see the blank result frame
