### ISSUE TITLE
Requested Improvements for Search

### ISSUE THREAD

**Issue by lizztheblizz** [vitessio/website#1166]
Thanks for taking the time to update the search plugin for the Docs website! Here are some thoughts, based on my day-to-day usage.

One challenge I have is I try to rely on search to bring me to pages I need to reference over and over again, i.e. `vtgate` flags or `vttablet` flags or `MoveTables`. The problem is our doc structure has many pages with mostly similar titles in very different sections. From just the title and the first paragraph (shown in the new search results), it’s hard to tell which page is coming up. Moreover, I have to scroll down to pick out the comparatively small “read more…” link to click through or identify the actual page being returned.

So, concrete suggestions are as follows:

- Increase clickthrough area for displayed search result beyond just the small "read more..." link.
- Include full page location for page in search result, either by display the link url, or by visualizing its content hierarchy.
- Reduce displayed text content for found page to allow more results to fit. Reduce font size.

Thanks!

**Comment by deepthi** [comment]
cc @thisisobate

**Comment by thisisobate** [comment]
Thanks for the feedback! @lizztheblizz 
I completely understand the issues you outlined above.
Will prioritize this work.

**Comment by thisisobate** [comment]
@deepthi Feel free to assign me to this one
