### ISSUE TITLE
Update contribution guides

### ISSUE THREAD

**Issue by deepthi** [vitessio/website#1192]
We have 3 guides:
https://vitess.io/docs/contributing/build-on-macos/
 - asks you to install `mysql@5.7`. we should remove the `@5.7` everywhere (4 occurrences).
https://vitess.io/docs/contributing/build-on-ubuntu/
- asks you to install go 1.17. Let us update that to go 1.18.
https://vitess.io/docs/contributing/build-on-centos/
- asks you to install go 1.17. Let us update that to go 1.18.

For golang, we may even want to say something like 
```
Install the a version of Golang that is at least the one listed here https://github.com/vitessio/vitess/blob/main/build.env#L20
```
And then say
```
For example, at writing, the version is go1.18.7 and this is how you install it.
```

**Comment by PaarthAgarwal** [comment]
Is it okay if I take on this issue? I can see it's already assigned, but it looks easy to solve.

**Comment by rsajwani** [comment]
@PaarthAgarwal , yes please go ahead and assign it to yourself. Add me and @frouioui as a reviewer.

**Comment by PaarthAgarwal** [comment]
> @PaarthAgarwal , yes please go ahead and assign it to yourself. Add me and @frouioui as a reviewer.

Thanks for the approval, I don't think I have access to change assignees but will tag you both on my PR.

**Comment by PaarthAgarwal** [comment]
@rsajwani I think this issue has been resolved already. Can you check?
