### ISSUE TITLE
[Docs Review] All VReplication Docs

### ISSUE THREAD

**Issue by rohit-nayak-ps** [vitessio/website#1212]
We are going to review all documentation related to VReplication during vitess release 16. This issue has a list of all pages on vitess.io related primarily to VReplication with tasks for each. 

### Concepts [Rohit]
https://vitess.io/docs/16.0/concepts/

- [x] Concepts: MoveTables
- [x] Concepts: VStream

### Design Docs [Rohit]
https://vitess.io/docs/design-docs/vreplication/

- [x] Design Doc: File:Position based VReplication
- [x] Design Doc: Life of a stream
- [x] Design Doc: Vstream
- [x] Design Doc: Character set support
- [x] Design Doc: How traffic is switched
- [x] Design Doc: Keys and iteration

#### Advanced Configuration  [Rohit]
https://vitess.io/docs/16.0/user-guides/configuration-advanced/

- [x] User Guide: Resharding
- [x] User Guide: CreateLookupVindex

#### Migration  [Matt]
https://vitess.io/docs/16.0/user-guides/migration/

- [x] User Guide: Migrating data into Vitess
- [x] User Guide: MoveTables
- [x] User Guide: Materialize
- [x] User Guide: Cutover Steps and Troubleshooting

#### Reference
https://vitess.io/docs/16.0/reference/vreplication/

- [x] Reference: Overview [Matt] https://github.com/vitessio/website/pull/1211
- [x] Reference: MoveTables
- [x] Reference: Reshard
- [x] Reference: --- Create
- [x] Reference: --- SwitchTraffic
- [x] Reference: --- ReverseTraffic
- [x] Reference: --- Complete
- [x] Reference: --- Show
- [x] Reference: --- Progress
- [x] Reference: --- Cancel
- [x] Reference: Materialize
- [x] Reference: VDiff
- [x] Reference: VDiff2
- [x] Reference: Workflow
- [x] Reference: VExec
- [x] Reference: VReplicationExec
- [x] Reference: VTTablet Flags
- [x] Reference: Metrics
- [x] Reference: Migrate
- [x] Reference: Mount
- [x] Reference: Shard Level Migrations
- [x] Reference: Tablet selection
- [x] Reference: Throttling
- [x] Reference: VReplication FAQ
- [x] Reference: VReplication V1 Commands

**Comment by mattlord** [comment]
Closing this as done since it's a duplicate and all Advanced Configuration are done, and that one is in progress.
