### ISSUE TITLE
[Docs Review] Review website (vitess.io) content.

### ISSUE THREAD

**Issue by rsajwani** [vitessio/website#1222]
This is the general, and tracking, issue for webiste (vitess.io) content review. The activity involves

1. Make sure the content reflect the current state and facts are up-to-date.
2. Add details if needed either in form of new section on current page or adding new page.

Please note that we are not going to focus of restructuring the website content as part of this project. It is something we will do as a separate project later on.

## Table of Contents

This content review is only for v15.0 and v16.0. 

This issue is considered done when each of these is complete

- [x] vitessio/website#1223
- [x] vitessio/website#1224
- [x] vitessio/website#1225
- [x] vitessio/website#1226
- [x] vitessio/website#1227
- [x] vitessio/website#1228
- [x] vitessio/website#1229
- [x] vitessio/website#1230
- [x] vitessio/website#1231
- [x] vitessio/website#1232
- [x] vitessio/website#1233
- [x] vitessio/website#1234
- [x] vitessio/website#1235
- [x] vitessio/website#1236
- [x] #1299 
- [x] #1300 
- [x] #1301 
- [x] vitessio/website#1237
- [x] vitessio/website#1238
- [x] vitessio/website#1239
- [x] vitessio/website#1240
- [x] vitessio/website#1241
- [x] vitessio/website#1242
- [x] vitessio/website#1243
- [x] #1244
- [x] #1245
- [x] #1246
- [x] #1247
- [x] #1248
- [x] #1249
- [x] #1250
- [x] #1251
- [x] #1252
- [x] #1254
- [x] #1255
- [x] #1256
- [x] #1257
- [x] #1258
- [x] #1259
- [x] #1260
- [x] #1261

## Instructions for changes

Website github url is https://github.com/vitessio/website. Instructions to run website locally is listed under the description there.

**Comment by frouioui** [comment]
@rsajwani, is this issue something we want to finish before the release of v16?

**Comment by rsajwani** [comment]
> @rsajwani, is this issue something we want to finish before the release of v16?

We should plan to do it end of December.
