### ISSUE TITLE
[Docs Review] Docs

### ISSUE THREAD

**Issue by rsajwani** [vitessio/website#1226]
Parent Issue vitessio/website#1222 
Vitess github url: https://github.com/vitessio/website

### Pages to review:
- [x] [docs](https://vitess.io/docs/)

### What to do 

- [ ] Make sure the content reflect the current state and facts are up-to-date.
- [ ] Add details if needed either in form of new section on current page or adding new page.
- [ ] Add links/Urls on page are working
- [ ] Deprecate flags should be marked as 'deprecated'
- [ ] Review is done for both V15 and V16 

Please note that we are not going to focus of restructuring the website content as part of this project. It is something we will do as a separate project later on.

**Comment by deepthi** [comment]
Same question as I had in #1227. I think we can close this one and #1226 because all the child sections / pages are covered by other issues.

**Comment by deepthi** [comment]
https://github.com/vitessio/website/issues/1227#issuecomment-1360170027
