### ISSUE TITLE
[Docs Review] v16.0 (Development)

### ISSUE THREAD

**Issue by rsajwani** [vitessio/website#1227]
Parent Issue vitessio/website#1222 
Vitess github url: https://github.com/vitessio/website

### Pages to review:
- [x] [v16.0 (Development)](https://vitess.io/docs/16.0/)
- [x] [v15.0](https://vitess.io/docs/15.0/)

### What to do 

- [ ] Make sure the content reflect the current state and facts are up-to-date.
- [ ] Add details if needed either in form of new section on current page or adding new page.
- [ ] Add links/Urls on page are working
- [ ] Deprecate flags should be marked as 'deprecated'
- [ ] Review is done for both V15 and V16

Please note that we are not going to focus of restructuring the website content as part of this project. It is something we will do as a separate project later on.

**Comment by deepthi** [comment]
@rsajwani what do I need to review here? We already decided not to tackle the organization of content in this round.
We seem to have separate issues for each section on this page anyway like #1229, #1228 etc. I can take some of those from you and/or Matt if necessary.

**Comment by rsajwani** [comment]
This is specifically for this landing pages 
https://vitess.io/docs/16.0/
https://vitess.io/docs/15.0/

yeah highly likely they will be no-op unless you feel some heading is missing etc.

**Comment by deepthi** [comment]
OK. I'm going to close this based on the comment from Rameez. We won't re-organize docs in this round, just fix up content. We can revisit this when we start a project to restructure the website/docs.
