### ISSUE TITLE
[Docs Review] Overview

### ISSUE THREAD

**Issue by rsajwani** [vitessio/website#1228]
Parent Issue vitessio/website#1222 
Vitess github url: https://github.com/vitessio/website

### Pages to review:

- [x] [Overview](https://vitess.io/docs/16.0/overview/) - Need to add "Why Vitess", but we have a separate issue for it #1217
- [x] [What Is Vitess](https://vitess.io/docs/15.0/overview/whatisvitess/)
- [x] [Architecture](https://vitess.io/docs/15.0/overview/architecture/)
- [x] [Supported Databases](https://vitess.io/docs/15.0/overview/supported-databases/) - need to update the version here to 8.0 as part of https://github.com/vitessio/vitess/pull/11989 
- [x] [Scalability Philosophy](https://vitess.io/docs/15.0/overview/scalability-philosophy/)
- [x] [Cloud Native](https://vitess.io/docs/15.0/overview/cloud-native/)
- [x] [History](https://vitess.io/docs/15.0/overview/history/)

### What to do 

- [x] Make sure the content reflect the current state and facts are up-to-date.
- [x] Add details if needed either in form of new section on current page or adding new page.
- [x] Add links/Urls on page are working
- [x] Deprecate flags should be marked as 'deprecated'
- [x] Review is done for both V15 and V16

Please note that we are not going to focus of restructuring the website content as part of this project. It is something we will do as a separate project later on.

**Comment by deepthi** [comment]
On the `What is Vitess` page we have this line
```
Query rewriting and sanitization – Add limits and avoid non-deterministic updates.
```
@vitessio/query-serving how do we avoid non-deterministic updates? Is this even something we still do?
