### ISSUE TITLE
[Docs Review] Get Started

### ISSUE THREAD

**Issue by rsajwani** [vitessio/website#1229]
Parent Issue vitessio/website#1222 
Vitess github url: https://github.com/vitessio/website

### Pages to review:

- [x] [Get Started](https://vitess.io/docs/16.0/get-started/)	
- [x] [Local Install via Docker](https://vitess.io/docs/15.0/get-started/local-docker/)
- [x] [Local Install](https://vitess.io/docs/15.0/get-started/local/)
- [x] [Local Install via Homebrew](https://vitess.io/docs/15.0/get-started/local-brew/)
- [x] [Vitess Operator for Kubernetes](https://vitess.io/docs/15.0/get-started/operator/)
- [x] [Local Install via source for Mac](https://vitess.io/docs/15.0/get-started/local-mac/)
- [x] [Vttestserver Docker Image](https://vitess.io/docs/15.0/get-started/vttestserver-docker-image/)

### What to do 

- [ ] Make sure the content reflect the current state and facts are up-to-date.
- [ ] Add details if needed either in form of new section on current page or adding new page.
- [ ] Add links/Urls on page are working
- [ ] Deprecate flags should be marked as 'deprecated'
- [ ] Review is done for both V15 and V16

Please note that we are not going to focus of restructuring the website content as part of this project. It is something we will do as a separate project later on.

**Comment by GuptaManan100** [comment]
There isn't an issue but an improvement that can be made. - https://github.com/vitessio/website/pull/1307 and https://github.com/vitessio/vitess/pull/12001
