### ISSUE TITLE
[Docs Review] VReplication User Guides

### ISSUE THREAD

**Issue by rsajwani** [vitessio/website#1234]
Parent Issue vitessio/website#1222 
Vitess github url: https://github.com/vitessio/website

### Pages to review:

- [x] [Migration](https://vitess.io/docs/15.0/user-guides/migration/)	
- [x] [Migrating data into Vitess](https://vitess.io/docs/16.0/user-guides/migration/migrate-data/)
- [x] [MoveTables](https://vitess.io/docs/16.0/user-guides/migration/move-tables/)
- [x] [Materialize](https://vitess.io/docs/16.0/user-guides/migration/materialize/)
- [ ] [Cutover Steps and Troubleshooting](https://vitess.io/docs/16.0/user-guides/migration/cutover/)

### What to do 

- [ ] Make sure the content reflect the current state and facts are up-to-date.
- [ ] Add details if needed either in form of new section on current page or adding new page.
- [ ] Add links/Urls on page are working
- [ ] Deprecate flags should be marked as 'deprecated'
- [ ] Review is done for both V15 and V16

Please note that we are not going to focus of restructuring the website content as part of this project. It is something we will do as a separate project later on.

**Comment by mattlord** [comment]
Just a note that I plan to begin working on this tomorrow. Hope to have a PR covering all the pages by the end of the week.
