### ISSUE TITLE
[Docs Review] Advanced Configuration

### ISSUE THREAD

**Issue by rsajwani** [vitessio/website#1236]
Parent Issue vitessio/website#1222 
Vitess github url: https://github.com/vitessio/website

### Pages to review:

- [x] [Advanced Configuration](https://vitess.io/docs/15.0/user-guides/configuration-advanced/)
- [x] [Tracing](https://vitess.io/docs/16.0/user-guides/configuration-advanced/tracing/)
- [x] [Unmanaged Tablet](https://vitess.io/docs/16.0/user-guides/configuration-advanced/unmanaged-tablet/)
- [x] [Securing Vitess Using TLS](https://vitess.io/docs/16.0/user-guides/configuration-advanced/transport-security-model/)

### What to do 

- [ ] Make sure the content reflect the current state and facts are up-to-date.
- [ ] Add details if needed either in form of new section on current page or adding new page.
- [ ] Add links/Urls on page are working
- [ ] Deprecate flags should be marked as 'deprecated'
- [ ] Review is done for both V15 and V16

Please note that we are not going to focus of restructuring the website content as part of this project. It is something we will do as a separate project later on.

**Comment by deepthi** [comment]
@rsajwani @GuptaManan100 everything is checked off. Can this be closed?

**Comment by GuptaManan100** [comment]
Yes, I think so. I am closing this.
