### ISSUE TITLE
[Docs Review] Making Schema Changes

### ISSUE THREAD

**Issue by rsajwani** [vitessio/website#1238]
Parent Issue vitessio/website#1222 
Vitess github url: https://github.com/vitessio/website

### Pages to review:

- [x] [Making Schema Changes](https://vitess.io/docs/15.0/user-guides/schema-changes/)
- [x] [Unmanaged Schema Changes](https://vitess.io/docs/16.0/user-guides/schema-changes/unmanaged-schema-changes/)
- [x] [Managed, Online Schema Changes](https://vitess.io/docs/16.0/user-guides/schema-changes/managed-online-schema-changes/)
- [x] [Online DDL strategies](https://vitess.io/docs/16.0/user-guides/schema-changes/ddl-strategies/)
- [x] [ddl_strategy flags](https://vitess.io/docs/16.0/user-guides/schema-changes/ddl-strategy-flags/)
- [x] [Table lifecycle](https://vitess.io/docs/16.0/user-guides/schema-changes/table-lifecycle/)
- [x] [Applying, auditing, and controlling Online DDL](https://vitess.io/docs/16.0/user-guides/schema-changes/audit-and-control/)
- [x] [Declarative migrations](https://vitess.io/docs/16.0/user-guides/schema-changes/declarative-migrations/)
- [x] [Postponed migrations](https://vitess.io/docs/16.0/user-guides/schema-changes/postponed-migrations/)
- [x] [Recoverable, failover agnostic migrations](https://vitess.io/docs/16.0/user-guides/schema-changes/recoverable-migrations/)
- [x] [Revertible migrations](https://vitess.io/docs/16.0/user-guides/schema-changes/revertible-migrations/)
- [x] [Concurrent migration execution](https://vitess.io/docs/16.0/user-guides/schema-changes/concurrent-migrations/)
- [x] [Advanced usage](https://vitess.io/docs/16.0/user-guides/schema-changes/advanced-usage/)

### What to do 

- [x] Make sure the content reflect the current state and facts are up-to-date.
- [x] Add details if needed either in form of new section on current page or adding new page.
- [x] Add links/Urls on page are working
- [x] Deprecate flags should be marked as 'deprecated'
- [ ] Review is done for both V15 and V16

Please note that we are not going to focus of restructuring the website content as part of this project. It is something we will do as a separate project later on.

**Comment by shlomi-noach** [comment]
Addressed by https://github.com/vitessio/website/pull/1297

**Comment by shlomi-noach** [comment]
ready to review!
