### ISSUE TITLE
Add new flag option pages

### ISSUE THREAD

**Issue by derekperkins** [vitessio/website#124]
Fairly often I want to reference flags for vtgate, vttablet, etc. We already have decent descriptions for the help docs, so it shouldn't be too difficult to output those to the website. We could copy them out for now, but it's probably best long term to autogenerate them from the main repo so they don't go stale.

I think that this is the perfect example: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/. It shows the flag, type and default value in an easy to reference table, hyperlinked to the description.

**Comment by hallaroo** [comment]
@deepthi / @derekperkins - I'm wondering if this older issue should be closed out as I think we have the reference tables on vitess.io now ❓ :

- https://vitess.io/docs/reference/programs/vtctl/ 
- https://vitess.io/docs/reference/programs/vttablet/#managed-mysql 
- https://vitess.io/docs/reference/programs/vtgate/ 
- https://vitess.io/docs/reference/programs/vtctld/

Unless any further changes need to be made to the reference tables on those pages? Thanks!

**Comment by derekperkins** [comment]
I didn't know those existed, I actually just went to the source code flag hunting last week. :) It'll be nice to add more documentation and guidance in the future per option, but they're great as is for now.
