### ISSUE TITLE
[Docs Review] Features

### ISSUE THREAD

**Issue by rsajwani** [vitessio/website#1240]
Parent Issue vitessio/website#1222 
Vitess github url: https://github.com/vitessio/website

### Pages to review:

- [x] [Features](https://vitess.io/docs/15.0/reference/features/) 
- [x] [Sharding](https://vitess.io/docs/15.0/reference/features/sharding/) @GuptaManan100 
- [x] [Sequences](https://vitess.io/docs/15.0/reference/features/vitess-sequences/) @GuptaManan100 
- [x] [VTGate Buffering](https://vitess.io/docs/15.0/reference/features/vtgate-buffering/) @GuptaManan100 
- [x] [Monitoring](https://vitess.io/docs/15.0/reference/features/monitoring/) @frouioui 
- [x] [MySQL Query Language Extensions](https://vitess.io/docs/15.0/reference/features/mysql-query-extensions/) @systay 
- [x] [Replication](https://vitess.io/docs/15.0/reference/features/mysql-replication/) @GuptaManan100 
- [x] [VSchema](https://vitess.io/docs/15.0/reference/features/vschema/) @GuptaManan100 
- [x] [Vindexes](https://vitess.io/docs/15.0/reference/features/vindexes/) @GuptaManan100 
- [x] [Two-Phase Commit](https://vitess.io/docs/15.0/reference/features/two-phase-commit/) @frouioui 
- [x] [Transport Security Model](https://vitess.io/docs/15.0/reference/features/transport-security-model/) @frouioui 
- [x] [Schema Routing Rules](https://vitess.io/docs/15.0/reference/features/schema-routing-rules/) @mattlord — https://github.com/vitessio/website/pull/1344
- [x] [Schema Management](https://vitess.io/docs/15.0/reference/features/schema-management/) @shlomi-noach - https://github.com/vitessio/website/pull/1350
- [x] [Schema Tracking](https://vitess.io/docs/15.0/reference/features/schema-tracking/) @frouioui 
- [x] [Point In Time Recovery](https://vitess.io/docs/15.0/reference/features/recovery/) @GuptaManan100 
- [x] [Topology Service](https://vitess.io/docs/15.0/reference/features/topology-service/) @frouioui 
- [x] [VTTablet Connection Pools and Sizing](https://vitess.io/docs/15.0/reference/features/connection-pools/) @GuptaManan100 
- [x] [Tablet throttler](https://vitess.io/docs/15.0/reference/features/tablet-throttler/) @shlomi-noach 
- [x] [Global Routing](https://vitess.io/docs/15.0/reference/features/global-routing/) @harshit-gangal 
- [x] [Vitess Messaging](https://vitess.io/docs/15.0/reference/features/messaging/) @GuptaManan100 

### What to do 

- [ ] Make sure the content reflect the current state and facts are up-to-date.
- [ ] Add details if needed either in form of new section on current page or adding new page.
- [ ] Add links/Urls on page are working
- [ ] Deprecate flags should be marked as 'deprecated'
- [ ] Review is done for both V15 and V16

Please note that we are not going to focus of restructuring the website content as part of this project. It is something we will do as a separate project later on.

**Comment by shlomi-noach** [comment]
Throttler docs reviewed in https://github.com/vitessio/website/pull/1305
