### ISSUE TITLE
[Docs Review] VTOrc

### ISSUE THREAD

**Issue by rsajwani** [vitessio/website#1248]
Parent Issue vitessio/website#1222 
Vitess github url: https://github.com/vitessio/website

### Pages to review:

- [x] [VTOrc](https://vitess.io/docs/15.0/reference/vtorc/)
- [x] [Architecture](https://vitess.io/docs/16.0/reference/vtorc/architecture/)
- [x] [Running with Vitess Operator](https://vitess.io/docs/16.0/reference/vtorc/running_with_vtop/)
- [x] [UI, API and Metrics](https://vitess.io/docs/16.0/reference/vtorc/ui_api_metrics/)

### What to do 

- [x] Make sure the content reflect the current state and facts are up-to-date.
- [x] Add details if needed either in form of new section on current page or adding new page.
- [x] Add links/Urls on page are working
- [x] Deprecate flags should be marked as 'deprecated'
- [x] Review is done for both V15 and V16

Please note that we are not going to focus of restructuring the website content as part of this project. It is something we will do as a separate project later on.

**Comment by GuptaManan100** [comment]
These docs are up-to-date.
