### ISSUE TITLE
[Docs Review] Design Docs

### ISSUE THREAD

**Issue by rsajwani** [vitessio/website#1254]
Parent Issue vitessio/website#1222 
Vitess github url: https://github.com/vitessio/website

### Pages to review:

- [x] [Design Docs](https://vitess.io/docs/design-docs/)

### What to do 

- [ ] Make sure the content reflect the current state and facts are up-to-date.
- [ ] Add details if needed either in form of new section on current page or adding new page.
- [ ] Add links/Urls on page are working
- [ ] Deprecate flags should be marked as 'deprecated'
- [ ] Review is done for both V15 and V16

Please note that we are not going to focus of restructuring the website content as part of this project. It is something we will do as a separate project later on.

**Comment by deepthi** [comment]
There are separate issues for each section of this page
#1257 
#1255 
#1256 
#1258 
etc.
I suggest we close this issue since each of those is assigned to various people.

**Comment by deepthi** [comment]
Based on discussion:
- VReplication design docs are more than just design at the time of implementation. They describe current behavior. Hence we should move them to `Internal` or something like that
- Most other design docs are historical. Current behavior / design is not the same as what is in the docs as things have evolved. So let us replace them with links to the markdown docs in the main repo (vitessio/vitess). See #1317

**Comment by rsajwani** [comment]
We will discuss it with Rohit next week...

**Comment by deepthi** [comment]
The query serving team has changed their design docs section to be links to GH issues/RFCs. This makes this page look weird and unbalanced now.
We should rework this so that each section can be clicked through to get to a list of docs, and this page is just a list of sections.
![Screenshot 2023-01-05 at 12 45 43 PM](https://user-images.githubusercontent.com/388311/210876988-823a49b3-0723-4d32-8e0c-3401f4c53aa4.png)

**Comment by deepthi** [comment]
Looks like the way our Hugo template works, if the md files are present in the sub directory, they will show up on this page.
~The only way to make them not show up is to remove them from there and keep them somewhere else (like vitessio/vitess/doc) and then link to those in each _index.md.
Even then, we'll have the ugly look of 6 sections with a horizontal line below them and no content unless we rework this page totally.~
It should be possible to re-work our Hugo template once we change the VRepl and VTTablet sections to make this better.

**Comment by deepthi** [comment]
A number of the child issues are closed. Let us leave this open until #1258 is complete and we can revisit whether the page layout needs to change.

**Comment by mattlord** [comment]
VReplication portion was completed in: https://github.com/vitessio/website/pull/1338
