### ISSUE TITLE
[Docs Review] VTTablet

### ISSUE THREAD

**Issue by rsajwani** [vitessio/website#1257]
Parent Issue vitessio/website#1222 
Vitess github url: https://github.com/vitessio/website

### Pages to review:

- [x] [VTTablet](https://vitess.io/docs/design-docs/vttablet/)
- [x] [Componentizing TabletServer](https://vitess.io/docs/design-docs/vttablet/component-ts/)
- [x] [Fast vttablet state transitions](https://vitess.io/docs/design-docs/vttablet/fast-transitions/)
- [x] [Real-time parameter change](https://vitess.io/docs/design-docs/vttablet/rt-params-change/)
- [x] [The tabletmanager model](https://vitess.io/docs/design-docs/vttablet/tm-model/)
- [x] [VTTablet with RBR mode](https://vitess.io/docs/design-docs/vttablet/rbr/)
- [x] [VTTablet YAML configuration](https://vitess.io/docs/design-docs/vttablet/tablet-params/)

### What to do 

- [x] Make sure the content reflect the current state and facts are up-to-date.
- [x] Add details if needed either in form of new section on current page or adding new page.
- [x] Add links/Urls on page are working
- [x] Deprecate flags should be marked as 'deprecated'
- [x] Review is done for both V15 and V16

Please note that we are not going to focus of restructuring the website content as part of this project. It is something we will do as a separate project later on.

**Comment by rsajwani** [comment]
Does all these VTTablet related documents (https://vitess.io/docs/design-docs/vttablet/) still hold true ?? Should we remove them or move them to RFC and link the (existing) RFC's over here. That way all the updates doesn't needs a website publish.

**Comment by rsajwani** [comment]
cc @deepthi @mattlord

**Comment by deepthi** [comment]
I like having them in the website. These docs are supposed to reflect the final state of the RFC, and they should not need to change after that. GH Issue RFCs get hard to read because we discuss and change things.

**Comment by deepthi** [comment]
Assigning myself to this.

**Comment by deepthi** [comment]
These are all historical documents. No changes are needed.

**Comment by deepthi** [comment]
https://github.com/vitessio/website/issues/1254#issuecomment-1368048178
