### ISSUE TITLE
[Docs Review] VReplication Design Docs

### ISSUE THREAD

**Issue by rsajwani** [vitessio/website#1258]
Parent Issue vitessio/website#1222 
Vitess github url: https://github.com/vitessio/website

### Pages to review:

- [x] [VReplication](https://vitess.io/docs/design-docs/vreplication/)	
- [x] [File:Position based VReplication](https://vitess.io/docs/design-docs/vreplication/file-pos/)
- [x] [Life of a stream](https://vitess.io/docs/design-docs/vreplication/life-of-a-stream/)
- [x] [Vstream](https://vitess.io/docs/design-docs/vreplication/vstream/)
- [x] [Schema Tracker](https://vitess.io/docs/design-docs/vreplication/vstream/tracker/)
- [x] [VStream Copy](https://vitess.io/docs/design-docs/vreplication/vstream/vscopy/)
- [x] [VStream API and Resharding](https://vitess.io/docs/design-docs/vreplication/vstream/stream-migration/)
- [x] [VStream Skew Minimization](https://vitess.io/docs/design-docs/vreplication/vstream/skew-detection/)
- [x] [Character set support](https://vitess.io/docs/design-docs/vreplication/character-sets/)
- [x] [How traffic is switched](https://vitess.io/docs/design-docs/vreplication/cutover/)
- [x] [Keys and iteration](https://vitess.io/docs/design-docs/vreplication/keys/)

### What to do 

- [ ] Make sure the content reflect the current state and facts are up-to-date.
- [ ] Add details if needed either in form of new section on current page or adding new page.
- [ ] Add links/Urls on page are working
- [ ] Deprecate flags should be marked as 'deprecated'
- [ ] Review is done for both V15 and V16

Please note that we are not going to focus of restructuring the website content as part of this project. It is something we will do as a separate project later on.

**Comment by mattlord** [comment]
Fixed in: https://github.com/vitessio/website/pull/1338
