### ISSUE TITLE
[Docs Review] Benchmark

### ISSUE THREAD

**Issue by rsajwani** [vitessio/website#1260]
Parent Issue vitessio/website#1222 
Vitess github url: https://github.com/vitessio/website

### Pages to review:

- [x] [Benchmark](https://vitess.io/docs/design-docs/benchmark/)
- [x] [arewefastyet](https://vitess.io/docs/design-docs/benchmark/arewefastyet/)

### What to do 

- [x] Make sure the content reflect the current state and facts are up-to-date.
- [x] Add details if needed either in form of new section on current page or adding new page.
- [x] Add links/Urls on page are working
- [x] Deprecate flags should be marked as 'deprecated'
- [x] Review is done for both V15 and V16

Please note that we are not going to focus of restructuring the website content as part of this project. It is something we will do as a separate project later on.

**Comment by frouioui** [comment]
> Each night, at midnight central european time, the head commit of your pull request will be benchmarked and compared against the pull request's base.

This is wrong, the current CRON for Pull Requests is set to every 5 minutes. We should actually link the CRON tables in the documentation.

**Comment by frouioui** [comment]
The rest of the two pages look good to me.

**Comment by frouioui** [comment]
@rsajwani, I will open a Pull Request to fix my comment (https://github.com/vitessio/website/issues/1260#issuecomment-1317926299).
