### ISSUE TITLE
[Docs Review] vtgate

### ISSUE THREAD

**Issue by rsajwani** [vitessio/website#1287]
Parent Issue vitessio/website#1222 
Vitess github url: https://github.com/vitessio/website

### Pages to review:

- [x] [Cell Aliases](https://vitess.io/docs/16.0/reference/programs/vtctl/cell-aliases/) @harshit-gangal 
- [x] [Cells](https://vitess.io/docs/16.0/reference/programs/vtctl/cells/) @harshit-gangal 
- [x] [Generic Commands](https://vitess.io/docs/16.0/reference/programs/vtctl/generic/) @harshit-gangal https://github.com/vitessio/website/pull/1310
- [x] [Keyspaces](https://vitess.io/docs/16.0/reference/programs/vtctl/keyspaces/) @harshit-gangal  https://github.com/vitessio/website/pull/1310
- [x] [Replication Graph](https://vitess.io/docs/16.0/reference/programs/vtctl/replication-graph/)
- [x] [Schema Versions & Permissions](https://vitess.io/docs/16.0/reference/programs/vtctl/schema-version-permissions/)
- [x] [Serving Graph](https://vitess.io/docs/16.0/reference/programs/vtctl/serving-graph/)
- [x] [Shards](https://vitess.io/docs/16.0/reference/programs/vtctl/shards/)
- [x] [vtexplain](https://vitess.io/docs/16.0/reference/programs/vtexplain/) @harshit-gangal https://github.com/vitessio/website/pull/1397
- [x] [vtgate](https://vitess.io/docs/16.0/reference/programs/vtgate/) @harshit-gangal https://github.com/vitessio/website/pull/1319
- [x] [vttablet](https://vitess.io/docs/16.0/reference/programs/vttablet/)  #1288 
- [x] vtaclcheck (new page)

### What to do 

- [x] Make sure the content reflect the current state and facts are up-to-date.
- [x] Add details if needed either in form of new section on current page or adding new page.
- [x] Add links/Urls on page are working
- [x] Deprecate flags should be marked as 'deprecated'
- [ ] Review is done for both V15 and V16

Please note that we are not going to focus of restructuring the website content as part of this project. It is something we will do as a separate project later on.

**Comment by rsajwani** [comment]
@vitessio/query-serving

**Comment by systay** [comment]
The title of this issue is vtgate, but the first couple of links are to `vtctl` pages. What am I missing?
