### ISSUE TITLE
Improving Website Analytics

### ISSUE THREAD

**Issue by harshit-gangal** [vitessio/website#1289]
Current Analytics on the Vitess Website seems very minimalistic. It gives us good insights about the top pages and demographics. 
But, it can be improved.

It is missing information about the search. About what users are searching for and what they landed on, how much time did they spend on those pages to understand if they landed on the right page or not?

About the flow of pages, users go through. 

This additional information will help us to understand if we should restructure our docs to make information more reachable to the users. 

---

(Edit) Link to the service desk ticket: [CNCFSD-1539](https://cncfservicedesk.atlassian.net/browse/CNCFSD-1539).

**Comment by harshit-gangal** [comment]
Raised the request on cncf service desk.

**Comment by chalin** [comment]
Hi @harshit-gangal. Before deep diving, I have a question to ask so that I can better understand your request.

> Current Analytics on the Vitess Website seems very minimalistic

Just to be clear: are you referring to Universal Analytics (UA) or Google Analytics 4 (GA4)?

/cc @nate-double-u

**Comment by harshit-gangal** [comment]
Hi @chalin
To my knowledge we use GA4

**Comment by deepthi** [comment]
We've been on GA4 since https://github.com/vitessio/website/issues/1098 was fixed.

**Comment by chalin** [comment]
Right, ok, I'm glad that we're on the same page, and all talking about GA4.

> Current Analytics on the Vitess Website seems very minimalistic. ... It is missing information about the search. ...

When I created the GA4 account, I enabled "Enhanced measurement", which includes events for **site search** and **file downloads**, so in that sense it is possible that nothing is missing. Here's an example for file downloads:

> <img width="1141" alt="image" src="https://user-images.githubusercontent.com/4140793/218561604-26c7b665-0cc7-4f54-9834-c5c626de8cc8.png">

It may be more a question of report generation. Feel free to explore the **Reports** and **Explore** sections of the GA4 console for Vitess. Let us know if that suits your needs.

**Comment by harshit-gangal** [comment]
@chalin I tried the `Explore` but I was not able to build a report with the `search term` as a dimension and `page views` 
 as metric.

**Comment by chalin** [comment]
In terms of getting analytics for search from within the site, since Lunr is used, we may indeed need a custom strategy. @thisisobate: might you know how to best hook up Google Analytics to Lunr search? I haven't found anything in yet. Of the top of my head, we could add a search query argument (`?search=<search-term-used>`) to each link in the results pane. WDYT?

In the meantime, have you looked at Search Console data?

**Comment by chalin** [comment]
@thisisobate - any updates? At a minimum we should discuss this at our next techdocs meeting. /cc @nate-double-u

**Comment by chalin** [comment]
Here's a status summary regarding the requests in the opening comment.

> It is missing information about the search. About what users are searching for 

(1) Regarding search terms, you can now view the [Event + search term](https://analytics.google.com/analytics/web/#/analysis/p323682739/edit/z108KkGAS3G7_xWyY9GibQ) report, here's a sample for the past 30 days (which you know about already, but for sake of completeness I'm listing it here):

> <img width="852" alt="image" src="https://github.com/vitessio/website/assets/4140793/cfe58b73-39bd-46bc-b78c-71e31a59fd09">

The report linked to above addresses the question "what are users searching for".

> and what they landed on, ...

(2) GA offers a standard [Landing page](https://analytics.google.com/analytics/web/#/p323682739/reports/explorer?params=_u..nav%3Dmaui&r=landing-page&ruid=landing-page,life-cycle,engagement&collectionId=life-cycle).

(3) To the best of my knowledge, **correlating searches with selected pages** would require more analytics **customization** (website **JS code**) as well as exporting to **Big Query** for the purpose of analyzing results. All of this would be considerable effort. I'm not sure it is worth the incremental gain as compared to what GA offers.

> how much time did they spend on those pages to understand if they landed on the right page or not?

(4) The Landing page  report includes **Average Engagement Time**.

> About the flow of pages, users go through.

(5) The Explorations section allows you to create "Path exploration" custom forms.

**Comment by chalin** [comment]
@harshit-gangal - you should have received a notice that the associated CNCF tick has been marked resolved. For a full explanation, see https://cncfservicedesk.atlassian.net/browse/CNCFSD-1539?focusedCommentId=27194. I've unassigned myself from this issue. Feel free to keep it open or close it as you see fit.

**Comment by harshit-gangal** [comment]
Closing as this is best can be done with "GA".
We can open a separate if issue if we want to go deeper as you suggested.
