### ISSUE TITLE
Add keyrange calculator

### ISSUE THREAD

**Issue by derekperkins** [vitessio/website#131]
It's not necessary, but it would be convenient if on the sharding page, there were a little calculator that would help you define your keyranges. I would input the number of desired shards, and it would output all of the shard names for an equal split.

**Comment by hallaroo** [comment]
Added a link to this reference to the sharding feature page: 

* The [vtctl GenerateShardRanges](../../../reference/programs/vtctl/shards/#generateshardranges) command-line tool supports generating shard ranges based on the provided number of shards.
