### ISSUE TITLE
Search not mobile friendly -- popup overflows view

### ISSUE THREAD

**Issue by chalin** [vitessio/website#1413]
- No popup appears after typing search text in the search input on mobile
- Possibly related? #1156

/cc @nate-double-u @thisisobate

**Comment by thisisobate** [comment]
@chalin Works on my end. Check the screenshot below...
@nate-double-u Can you help me check on your end too?
<img width="1242" alt="Screenshot 2023-03-21 at 19 50 20" src="https://user-images.githubusercontent.com/29557702/226711955-21a8ab10-00cb-41d4-8693-290688f12e00.png">

**Comment by nate-double-u** [comment]
I also see a popup. Using Safari on an iPhone SE running iOS version 16.3.1

![IMG_5384](https://user-images.githubusercontent.com/4453979/227061589-0f1689bb-2911-46d0-8aae-da0b867b6d07.PNG)

**Comment by chalin** [comment]
Oh, strange! Yes, it is working for me now.

Though now I'm seeing that the popup overflows the view width.
@thisisobate - could you fix that? (I've changed the issue title to focus on the layout issue.)

**Comment by thisisobate** [comment]
sure...pushing a fix right away
