### ISSUE TITLE
Style/design: cannot distinguish quoted code that is also a link from quoted code that is not.

### ISSUE THREAD

**Issue by shlomi-noach** [vitessio/website#1449]
On the Vitess website, you can't tell if a quoted code is link or not, until you hover with the cursor. A link should be distinguishable.

Consider the below sample content:

```
[This text](http://example.com/) will appear blue, compared with the black color for normal text.
`This code quote` has a gray background, and that's fine.
[`MyGolangStruct`](http://example.com/) has a gray background, and no indication that it's also a link. You only find out it's a link when you hover and see the mouse cursor change. I'd expect it to be blue or something else that is distinct.
```

As a visual example, consider the below: `CREATE TABLE` in the below, is not a link. `CreateTable` is. You can't tell the difference.

![image](https://user-images.githubusercontent.com/2607934/233375270-2a84bb3b-0b39-4186-a6e3-9ff775b43c64.png)

Ideally a linked quoted code will have a blueish text.

**Comment by deepthi** [comment]
@nate-double-u @chalin @thisisobate can one of you help us with this?

**Comment by J0SAL** [comment]
Hii @shlomi-noach , I would like to work on this issue, could you please assign this to me

**Comment by shlomi-noach** [comment]
@J0SAL thank you. Just to verify, as you have never contributed to vitess/docs in the past: you wish to help with CSS/design for a documentation project in a repo owned by CNCF. The project is licensed with [Apache 2](https://github.com/vitessio/website/blob/prod/LICENSE).

We've already pinged specific people on this; I'm happy to assign this to you, but then I will also place a time limit on this assignment, just because of past experience with other contributors who have gone dark. Is it OK to assign this to you for 7 days, then if nothing happens unassign? Please let me know.

**Comment by J0SAL** [comment]
@shlomi-noach yes sure.. it works👍
