### ISSUE TITLE
Vitess 17 Local Install instructions not working.

### ISSUE THREAD

**Issue by jfg956** [vitessio/website#1520]
### Overview of the Issue

Hi, I am running the Vitess 17 Local Install {1} and I am getting a `No such file or directory` when doing `cd ~/my-vitess-example/examples/local`.  See Reproduction Steps for more details.

{1}: https://vitess.io/docs/17.0/get-started/local/

My guess is that the instructions should be to `mkdir ~/my-vitess-example` (instead to `mkdir -p ~/my-vitess-example/examples`0 and to `cp -r <vitess source path>/examples ~/my-vitess-example` instead of `cp -r <vitess source path>/examples ~/my-vitess-example/examples`.

From what I understand, there is the same problem in the doc for Vitess 16 {2} and 15 {3}.

{2}: https://vitess.io/docs/16.0/get-started/local/
{3}: https://vitess.io/docs/15.0/get-started/local/

I will probably submit a PR to fix this.

### Reproduction Steps

$ mkdir -p ~/my-vitess-example/examples
$ cd ~/vitess
$ cp -r examples ~/my-vitess-example/examples
$ cp -r web ~/my-vitess-example
$ cd ~/my-vitess-example/examples/local
bash: cd: /home/jgagne/my-vitess-example/examples/local: No such file or directory

### Binary Version

```sh
$ vtgate --version
Version: 17.0.0 (Git revision 70a94669826071e31f4ac14047de911753f4af5d branch 'HEAD') built on Tue Jun 27 13:20:18 UTC 2023 by runner@fv-az1098-397 using go1.20.5 linux/amd64
```

**Comment by jfg956** [comment]
Fixed in below PR.
https://github.com/vitessio/website/pull/1521

**Comment by mattlord** [comment]
Fixed by https://github.com/vitessio/website/pull/1521
