### ISSUE TITLE
Old links breaking with archival

### ISSUE THREAD

**Issue by vahe** [vitessio/website#1639]
As old versions are getting archived, the existing links break. Example, after https://github.com/vitessio/website/pull/1637 docs at the old path 404: https://vitess.io/docs/15.0/user-guides/configuration-basic/vtgate/.

Would be nice to keep the old links working but still be explicit that they're archived.

**Comment by deepthi** [comment]
To piggy back on this issue, we also need a redirect for the old blog post URL for v19 to point to the new one. It was changed after release because it had the old date.

**Comment by Satarupa22-SD** [comment]
@deepthi can you please assign this issue to me if it's still open. Thanks

**Comment by frouioui** [comment]
This was fixed via https://github.com/vitessio/website/pull/1771 back in June. Closing for now, if you are still experiencing the issue, feel free to re-open.
