### ISSUE TITLE
Remove SBR support

### ISSUE THREAD

**Issue by derekperkins** [vitessio/website#168]
- [x] remove all schema swap documentation
- [x] remove references to SBR
- [ ] put up a banner with an SBR deprecation notice

**Comment by skinnylatte** [comment]
assigning myself to this issue.

**Comment by morgo** [comment]
This was fixed in https://github.com/vitessio/website/pull/237

I did not explicitly say deprecated for SBR, but that RBR is required:
https://vitess.io/docs/reference/mysql-replication/

I am going to close this issue now.
