### ISSUE TITLE
FAQ: Common Scenarios

### ISSUE THREAD

**Issue by skinnylatte** [vitessio/website#173]
Relating to [the thread](https://github.com/vitessio/vitess/issues/2811) with @sabutai's question on Slack (referencing this [issue](https://github.com/vitessio/vitess/issues/2811)):

* Add info about the workaround

```
sabutai   [15 hours ago]
For others who may be interested: We've found a workaround for this: By using Eclipselink QuerySequence, we were able to define a query to Vitess Sequences tables directly. This not only prevented SELECT LAST_INSERT_ID() call, we were also able to reduce number of DB trips since the application could request a bunch of IDs from Vitess, let's say 1000, so it will make only one call per 1000 inserts.
```

action: put faq for common scenarios back online

**Comment by hallaroo** [comment]
Added to Freshdesk here: https://planetscale.freshdesk.com/a/solutions/articles/64000257911
