### ISSUE TITLE
Review and improve Getting Started guides

### ISSUE THREAD

**Issue by deepthi** [vitessio/website#1738]
We have had the Getting Started guides for a while. It is time to re-run them and make sure that everything still works as expected.

**Comment by asr2003** [comment]
@deepthi Any updates on this issue? I'd like to work on this issue

**Comment by frouioui** [comment]
Related to https://github.com/vitessio/website/issues/1798. We are proposing an LFX project to work on this for the 3rd term of 2024.

**Comment by asr2003** [comment]
Thanks @frouioui for the info! I thought it is another issue apart from it :)

**Comment by asr2003** [comment]
Any guidance on how to get started will be greatful. Maybe a pretest or technical design doc to know more about vitess

**Comment by deepthi** [comment]
This particular issue is already being worked on. Please note that It is not part of the scope of LFX term 3, it's just related. PRs are still welcome for things I might miss as improvements.
