### ISSUE TITLE
 Update README with Community and Contributing sections

### ISSUE THREAD

**Issue by Ayush9026** [vitessio/website#1742]
## Description:
Please update the README.md file by adding dedicated sections for Community and Contributing. These sections are crucial for providing information to new contributors and fostering a collaborative environment within our project.

**Task:**
Include information about our community, such as how to join, communicate, and get involved.
Include guidelines for contributing to the project, such as code formatting, pull request process, and code of conduct.

**Comment by Satarupa22-SD** [comment]
@mattlord please assign this issue to me. Thanks

**Comment by mattlord** [comment]
@Satarupa22-SD I appreciate the interest, but I'm going to close this one as we decided that there's really no need to add this to the README as it's elsewhere provided elsewhere. I'm happy to help you find another ticket if you're interested. ❤️
