### ISSUE TITLE
Add Social Media Icons with Links to README

### ISSUE THREAD

**Issue by Ayush9026** [vitessio/website#1745]
## Description:
To enhance the visibility and accessibility of Vitess's social media presence, it would be beneficial to add social media icons with their respective links to the README file. This will help users easily connect with Vitess on various platforms, stay updated with the latest news, and engage with the community.

**Benefits:**

- Increases engagement by providing direct links to Vitess's social media profiles.

- Encourages users to follow and interact with Vitess on multiple platforms.

- Enhances the overall user experience by keeping the community connected

**Comment by Satarupa22-SD** [comment]
@mattlord please assign this issue to me.

**Comment by Satarupa22-SD** [comment]
@mattlord please close this issue. Thanks

**Comment by mattlord** [comment]
> @mattlord please close this issue. Thanks

Will do. Sorry, I had meant to do this earlier but it fell through the cracks (too many things going on). 

Closing this as we decided against copying this kind of stuff from the website into the code repo.
