### ISSUE TITLE
Add CODE_OF_CONDUCT.md to Repository

### ISSUE THREAD

**Issue by Ayush9026** [vitessio/website#1751]
## Description:

**Overview :**
To foster a welcoming and inclusive community, I propose adding a CODE_OF_CONDUCT.md file to the Vitess website repository. This file will outline expected behavior and guidelines for maintaining a positive environment.

**Objectives :**

1. Promote Inclusivity: Establish clear behavior guidelines.
2. Provide Support: Offer a framework for reporting incidents.
3. Foster Community Spirit: Encourage respect and collaboration.

**Conclusion**

Adding a CODE_OF_CONDUCT.md file will ensure a positive and inclusive environment for all Vitess community members.

**Comment by deepthi** [comment]
We already have a [code of conduct in the main repo](https://github.com/vitessio/vitess/blob/main/CODE_OF_CONDUCT.md). Why would we duplicate it here?

**Comment by Ayush9026** [comment]
Thank you mam for pointing that out.
