### ISSUE TITLE
Update Twitter Icon to X in Header and Footer

### ISSUE THREAD

**Issue by Ayush9026** [vitessio/website#1754]
## Description:
We need to update the Twitter icon in both the header and footer of our website to reflect the change to X Corp. Currently, the icon is linked to our old Twitter account, and we want to ensure consistency across all our branding and social media platforms.

**Additional Notes:**

Marked in screenshot 

![Vitess website](https://github.com/vitessio/website/assets/114745463/46b08054-cf6e-4d32-b333-32f449c46729)

**Comment by Satarupa22-SD** [comment]
@Ayush9026 can you assign this issue to me in case you are not working on this . Thanks!

**Comment by frouioui** [comment]
This was implemented in https://github.com/vitessio/website/pull/1813, closing for now.
