### ISSUE TITLE
Revamp highlights on website homepage

### ISSUE THREAD

**Issue by deepthi** [vitessio/website#1784]
It will be nice to revamp the main homepage to highlight features that may be more relevant today compared to 5 years ago.

Current state:

![Screenshot](https://github.com/vitessio/website/assets/388311/f8ba190a-9445-4523-b9f1-82389911e85d)

To start with I'm going to document some of the suggestions that have come up. We can have some discussion on this issue and then finalize the 6 highlights we want to have with associated text.

- Online schema changes
- While Shard management sort of gets at this, we want to highlight how easy it is to migrate into Vitess, and to "MoveTables", with close to zero downtime.
- High availability is missing (sort of covered under Manageability by saying "Failovers")
- Backups and restores should be their own highlight
- Connection Pooling can become a feature under performance instead of its own section.
- Workflow can probably be removed
- Materialized Views
- Messaging
- Vindexes aka flexible sharding keys. We say "without adding sharding logic to application", but don't highlight how flexible vitess sharding is

Thanks to @timvaillancourt for raising this and providing many of these suggestions. And to @derekperkins and @shlomi-noach for their follow up suggestions and commentary.

**Comment by anshikavashistha** [comment]
@deepthi As mentioned above ,Online schema changes need to be highlighted as per this reference ,[Online DDL](https://vitess.io/docs/archive/16.0/user-guides/schema-changes/audit-and-control/).

**Comment by anshikavashistha** [comment]
@deepthi May I contribute on this issue as per your instructions?
Would love to contribute
