### ISSUE TITLE
Survey/Poll questions

### ISSUE THREAD

**Issue by deepthi** [vitessio/website#1785]
We want to conduct a user survey to collect feedback from the community. We can use this to improve documentation and inform roadmap decisions. The list of questions is only a start, we can add to it and finalize it before actually conducting the survey.

Q: How will the survey be conducted?
A: Most likely through a google form. We'll have to figure out how to process the responses so that we can extract insights from them

List of questions:
1. How long have you been using Vitess?
1. Are you running Vitess in production?
1. If yes, for how long?
1. Which version of Vitess are you running?
1. How often do you upgrade your Vitess version?
1. How often do you upgrade your MySQL version? Including 8.0 minor version upgrades.
1. Which version of MySQL are you running? Percona / Oracle, 5.7 / 8.0
1. Which version of MySQL do you plan to upgrade to next?
1. How soon do you plan to upgrade to the next MySQL version? Within the next 6 months? 6 months to 1 year? > 1 year?
1. How is it deployed? Kubernetes, VMs, something else?
1. How is it deployed? Cloud or on-prem?
1. How big is your vitess deployment? Number of keyspaces, shards, average shard data size, number of replicas per shard.
1. Have you run a resharding process?
1. If yes, reason for resharding? data size / replication delay / IOPS / write contention / Other (please specify)
1. What is your favorite Vitess feature?
1. In your opinion, what is the biggest missing feature?

**Comment by kirtanchandak** [comment]
@deepthi If the questions are final, then should I start preparing the form? 

And should I go ahead with Google forms?

**Comment by deepthi** [comment]
Let's wait another day or so and then finalize the questions.

**Comment by deepthi** [comment]
Survey has been published.
