### ISSUE TITLE
Incorrect page forward

### ISSUE THREAD

**Issue by bddicken** [vitessio/website#1787]
When visiting this URL:

https://vitess.io/docs/reference/features/vtgate-buffering/

I expect it to forward me to the associated page for the current version of Vitess. In this case, the v20 page:

https://vitess.io/docs/20.0/reference/features/vtgate-buffering/

However, it takes me here instead:

https://vitess.io/docs/archive/17.0/user-guides/configuration-advanced/buffering-scenarios/

This seems incorrect.

**Comment by anshikavashistha** [comment]
@bddicken I would like to work on this issue

**Comment by anshikavashistha** [comment]
Could you please assign it to me ?
@bddicken

**Comment by shailpujan88** [comment]
@bddicken I would like to work on this issue. Can you please assign it to me?

**Comment by mattlord** [comment]
@anshikavashistha are you still working on this?

**Comment by shailpujan88** [comment]
Hey @mattlord Can you please assign it to me?

**Comment by anshikavashistha** [comment]
Yes I am 
@mattlord

**Comment by anshikavashistha** [comment]
PTAL @bddicken

**Comment by frouioui** [comment]
Fixed by #1834

**Comment by frouioui** [comment]
Works as expected after the new deploy:

https://vitess.io/docs/reference/features/vtgate-buffering/

Redirects to

https://vitess.io/docs/20.0/reference/features/vtgate-buffering/
