### ISSUE TITLE
VSchema advanced usage is inconsistent with tutorial

### ISSUE THREAD

**Issue by deepthi** [vitessio/website#179]
https://vitess.io/docs/schema-management/vschema/#advanced-usage
Since we changed the local example (vitessio/vitess/examples/local), this part of the documentation is now out-of-date. The new local example does not actually illustrate the advanced usage, so we may need to enhance that.
Or possibly this will be covered by the vreplication example once we are able to mainstream that.

**Comment by hallaroo** [comment]
This page is no longer available. Thus closing this issue out.
