### ISSUE TITLE
Reorganize resources page and make it easier to navigate

### ISSUE THREAD

**Issue by deepthi** [vitessio/website#1850]
We have a bunch of videos and presentations on this page https://vitess.io/docs/learning-resources/
It's not very easy to navigate. It will be nice to lay the content out in some fashion that doesn't need you to scroll forever.
Also, we used to have a right-nav to jump to each section, and that seems to have somehow got lost when we merged #1793

**Comment by thisisobate** [comment]
Hi @deepthi @frouioui 
Just going through the resource page and indeed, it's not very easy to navigate. I'm considering implementing a filter for this page. This will enable us filter by different categories such as resource type and year.

We did something similar for [Flux](https://fluxcd.io/resources/).

What do you think?

**Comment by frouioui** [comment]
@thisisobate, I really like the idea of having filters. In the future would we be able to add more filters, for instance if we want to add a "category" filter (query serving, introduction, demo, performance, etc)?

Also the grid layout used on the Flux website makes the navigation easier, we wouldn't have to scroll forever to reach the bottom.

**Comment by thisisobate** [comment]
> In the future would we be able to add more filters, for instance if we want to add a "category" filter (query serving, introduction, demo, performance, etc)?

Oh yes, definitely.

**Comment by frouioui** [comment]
@thisisobate, I think it sounds good then.
