### ISSUE TITLE
Multiple vtgate setups in local machine using docker

### ISSUE THREAD

**Issue by SapanShiv** [vitessio/website#198]
Hi Team,

Please help me with the steps of configuring multiple vtgates in my local machine through docker.
Is it possible to do so?

**Comment by morgo** [comment]
@SapanShiv Thanks for reaching out.

We do not have current plans for documenting a tutorial involving multiple vtgates with Docker. We do however have plans to better document a multi-cell deployment, which will use multiple vtgates. You can track the progress in https://github.com/vitessio/website/issues/249
