### ISSUE TITLE
Add Vitess Calendar to Vitess website 

### ISSUE THREAD

**Issue by lkburns** [vitessio/website#199]
We have created a Vitess Calendar that lists the Vitess Monthly Meetings and will list Vitess Meetups. 

We would like to make this available on the Vitess website so that the Vitess Community can add it to their calendars and stay up-to-date on events. 

https://calendar.google.com/calendar/embed?src=planetscale.com_21541iv1dn67m0jd023lql4dak%40group.calendar.google.com&ctz=America%2FLos_Angeles

**Comment by raunaqgupta** [comment]
We can add a link on this page: https://vitess.io/community/

**Comment by morgo** [comment]
This has been done.
