### ISSUE TITLE
Add recent content to Resources page

### ISSUE THREAD

**Issue by deepthi** [vitessio/website#213]
The Resources page has content up to October 2018. We should add the following recent content:
- Derek Perkins / Nozzle.io on Cloud Native show
https://anchor.fm/cloud-native-show/episodes/Vitess-at-scale---how-Nozzle-io-runs-MySQL-on-Kubernetes-e4m5lo
- Sugu CNCF Webinar https://youtu.be/E6H4bgJ3Z6c
- JD.com at Kubecon 19 China 
  How JD.Com runs the World's Largest Vitess 
  https://www.youtube.com/watch?v=qww4UVNG3Io
- Jiten at RootConf
  OLTP or OLAP: why not both? https://youtu.be/bhzJJF82mFc
- Sugu @ Percona Live https://www.youtube.com/watch?v=v7oxiVmGXp4
- David Cohen (Intel) @ Percona Live 
https://www.percona.com/live/19/sessions/an-open-source-cloud-native-database-cndb
- Vitess Deep Dive @ Kubecon 19 Europe https://www.youtube.com/watch?v=OZl4HrB9p-8
- Meetup at Slack HQ, co-hosted by Planetscale
  - Vitess: New and Coming Soon! Deepthi Sigireddi (TODO: get slides from @deepthi)
  - Deploying multi-cell Vitess, Rafael Chacon Vivas (TODO: get slides from @rafael)
  - Vitess at Pinterest, David Weitzman https://www.youtube.com/watch?v=1cWWlaqlia8
  - No more Regrets, Sugu https://www.youtube.com/watch?v=B1Nrtptjtcs

**Comment by deepthi** [comment]
There are also recordings on youtube of the Intro to Vitess & Deep Dive into Vitess from Kubecon China. The content of those videos is duplicated in other talks, but it might be helpful to chinese users.

**Comment by sougou** [comment]
The webinar: https://youtu.be/E6H4bgJ3Z6c

**Comment by morgo** [comment]
I have a branch for this here: https://github.com/vitessio/website/pull/242

@deepthi @rafael Do you mind sharing a link to slides?
