### ISSUE TITLE
Document ApplyVSchema changes

### ISSUE THREAD

**Issue by morgo** [vitessio/website#245]
Via https://github.com/vitessio/vitess/pull/4868 and https://github.com/vitessio/vitess/pull/5010

A blank vschema is now required. We should make sure there is an example here:
https://vitess.io/docs/schema-management/vschema/#applyvschema

**Comment by hallaroo** [comment]
This is now available here: https://vitess.io/docs/reference/features/vschema/#sharded-keyspaces-require-a-vschema
