### ISSUE TITLE
"Manual build" is no longer manual build

### ISSUE THREAD

**Issue by morgo** [vitessio/website#246]
On https://vitess.io/ the link to "Manual Build" goes to the local tutorial, which was previously a manual build -- now it uses packages. The manual build is now under contributing.

I think we should change it to "Local Install", in which case the icon should probably change.

**Comment by raunaqgupta** [comment]
How does this look for a local server?

![Screenshot_2019-08-01 The Noun Project](https://user-images.githubusercontent.com/623670/62323433-1becb780-b45c-11e9-8e65-d662abea6c37.png)

**Comment by raunaqgupta** [comment]
@morgo Thoughts?

![Local Install](https://user-images.githubusercontent.com/623670/62405389-9a775100-b551-11e9-86d0-374b3af588ec.png)

**Comment by morgo** [comment]
LGTM
