### ISSUE TITLE
Replace: Getting Started with k8s

### ISSUE THREAD

**Issue by skinnylatte** [vitessio/website#26]
Replace: "[getting started with Kubernetes](https://vitess-io.netlify.com/docs/getting-started/kubernetes/)" with just one command.

@sougou - what is it? :)

**Comment by sougou** [comment]
i'm still making changes. Most likely, it will be:
```
cd examples/helm
helm install ../../helm/vitess -f phases/phase1.yaml
```
But then there are other phases for vertical splits etc. Code is still WIP.
