### ISSUE TITLE
xtrabackup is not documented

### ISSUE THREAD

**Issue by morgo** [vitessio/website#261]
See: https://vitess.io/docs/user-guides/backup-and-restore/ -- there is no mention of the xtrabackup plugin.

**Comment by J0** [comment]
Fixed by #289

**Comment by deepthi** [comment]
The documentation is wrong. xtrabackup is not another value of `backup_storage_implementation`. There is another flag called `backup_engine_implementation` which takes values `builtin` or `xtrabackup`. There are also a number of flags specific to xtrabackup that need to be documented.
See https://github.com/vitessio/vitess/pull/4695 and https://github.com/vitessio/vitess/pull/5065

**Comment by hwang381** [comment]
opened PR to fix the doc #310
