### ISSUE TITLE
Write transport security guide with end to end TLS example

### ISSUE THREAD

**Issue by morgo** [vitessio/website#276]
<strike>
On https://vitess.io/docs/user-guides/transport-security-model/ , there is no configuration example for topo server. Since etcd is the default we should show an example that is end-to-end with certificates.

etcd configuration is:
https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/security.md
</strike>

The previous guide has been moved to reference, we need to write a new guide with end to end TLS configuration.

**Comment by hallaroo** [comment]
We now have this guide: https://vitess.io/docs/user-guides/configuration-advanced/transport-security-model/
