### ISSUE TITLE
Replace Expired Vitess Slack Channel Invitation Link on Vitess Homepage

### ISSUE THREAD

**Issue by lkburns** [vitessio/website#292]
The invite link for the Vitess Slack Channel changed. 

Please update the Slack links in both the header and footer with this link:

https://join.slack.com/t/vitess/shared_invite/enQtMzIxMDMyMzA0NzA1LTYxMjk2M2M2NjAwNGY0ODljY2E1MjBlZjRkMmZmNDVkZTBhNDUxNzNkOGM4YmEzNWEwOTE2NjJiY2QyZjZjYTE

**Comment by lkburns** [comment]
@raunaqgupta if you have bandwidth to fix this in advance of PerconaLive, that would be really helpful! Slack changed the structure URLs, which is why this one no longer works.

**Comment by morgo** [comment]
I believe this is fixed. Closing.
