### ISSUE TITLE
Document pool sizes better

### ISSUE THREAD

**Issue by morgo** [vitessio/website#302]
Connection pools can create opaque performance characteristics.

The settings AppConnPoolMaxCap, ConnPoolMaxCap, DbaConnPoolMaxCap, FoundRowsPoolMaxCap, MessagerPoolMaxCap, StreamConnPoolMaxCap, TransactionPoolMaxCap, TxReadPoolMaxCap should not be set to larger than MySQL's `max_connections`. (aside: It would be nice to also validate config to ensure this is true, but may not be straight forward in cases such as externally managed tablets.)

We should also have pool sizing recommendations and observability guidelines.

**Comment by hallaroo** [comment]
move the pool doc written here in: https://github.com/aquarapid/vitess_examples/tree/master/pools

**Comment by hallaroo** [comment]
That doc has been added here: https://vitess.io/docs/reference/features/connection-pools/
