### ISSUE TITLE
Make sure that kubernetes get-started guide works on macOS

### ISSUE THREAD

**Issue by morgo** [vitessio/website#349]
We should verify that the instructions here work on macOS as well (Darwin arm64 and amd64): https://vitess.io/docs/get-started/operator/

**Comment by J0** [comment]
I'm following the update process in the docs now; I'll report back if there are any errors.

**Comment by J0** [comment]
*Notes*
1. After installing, `run helm init`
Current version of helm on brew (helm v3.0) doesn't have  an `init` command
