### ISSUE TITLE
Can't find monthly newsletter signup

### ISSUE THREAD

**Issue by riking** [vitessio/website#392]
I need to change the email address I receive the newsletter at, and I do not see a signup link on https://vitess.io/community/ .

**Comment by riking** [comment]
issue is invalid, I was looking for the planetscale newsletter. Still can't find the signup form though

**Comment by raunaqgupta** [comment]
Hi @riking, if you are still interested, you can find a newsletter signup form on the footer at www.planetscale.com. Prior to this, we were sending out the newsletter to anyone who had either contacted us via the website or signed up for PlanetScaleDB (at console.planetscale.com and checked the newsletter subscription checkbox). If you had done either of those, I hope you have been getting our newsletter. If not, you can now signup to the newsletter via the website.
