### ISSUE TITLE
Presentations page no longer embedding PDFs

### ISSUE THREAD

**Issue by morgo** [vitessio/website#421]
On the [presentations page](https://vitess.io/docs/resources/presentations/), there used to be embedded PDFs.

I am not really sure when it stopped working (it might be a browser update on my side, or some of the recent CSS tweaks). I noticed it when working on #420

@celestehorgan @lucperkins do you mind investigating?

**Comment by morgo** [comment]
I checked out an old branch, and it does appear to be working. So it looks like something specifically broke it. I noticed that [this page](https://vitess.io/docs/contributing/github-workflow/) also isn't showing the image that was on it.

**Comment by celestehorgan** [comment]
I'll take a look at this and see what there is to see.

**Comment by celestehorgan** [comment]
This apparently has to do with a Hugo version bump – see [here](https://discourse.gohugo.io/t/raw-html-getting-omitted-in-0-60-0/22032). 

The solution described (adding a `[markup.goldmark.renderer]
unsafe= true` to `config.toml`) works, but it's probably better in the long run to make you guys a custom Hugo shortcode for this embed and use less inline HTML. I'll open a PR shortly :)

**Comment by morgo** [comment]
Ahh, thanks for the heads up!

I am going to go ahead and re-enable for now in https://github.com/vitessio/website/pull/425 -- there look to be a lot of cases that will need fixing. I will have to create an umbrella issue to handle them before we can go back to blocking unsafe.

**Comment by celestehorgan** [comment]
@morgo That seems like a good idea to me, too, and a far more organized way to handle this :)
