### ISSUE TITLE
Document: External DB RDS

### ISSUE THREAD

**Issue by chrisrgithub** [vitessio/website#436]
Enclosed are draft Guide input files, for basic demonstration of vitess with RDS.  They provide RDS creation instructions and additional files to work with vitess examples/local.
[vitess_external_rds.zip](https://github.com/vitessio/website/files/4499771/vitess_external_rds.zip)

**Comment by kristee-planetscale** [comment]
closing and combining with issue https://github.com/vitessio/website/issues/532
