### ISSUE TITLE
Document: External DB Aurora

### ISSUE THREAD

**Issue by chrisrgithub** [vitessio/website#437]
Enclosed are draft Guide input files, for basic demonstration of vitess with Aurora. They provide Aurora creation instructions and additional files to work with vitess examples/local.
[vitess_external_aurora.zip](https://github.com/vitessio/website/files/4500543/vitess_external_aurora.zip)

**Comment by kristee-planetscale** [comment]
closing and combining with issue https://github.com/vitessio/website/issues/532
