### ISSUE TITLE
Document: External DB CloudSQL

### ISSUE THREAD

**Issue by chrisrgithub** [vitessio/website#438]
Enclosed are draft Guide input files, for basic demonstration of vitess with CloudSQL. They provide CloudSQL creation instructions and additional files to work with vitess examples/local.
[vitess_external_cloudsql.zip](https://github.com/vitessio/website/files/4500598/vitess_external_cloudsql.zip)

**Comment by kristee-planetscale** [comment]
closing and combining with issue https://github.com/vitessio/website/issues/532
