### ISSUE TITLE
Document: vtgate with SSL/TLS

### ISSUE THREAD

**Issue by chrisrgithub** [vitessio/website#439]
Enclosed are draft Guide input files, for basic demonstration of vtgate over SSL/TLS. They provide PKI creation instructions for the necessary certs and keys to use with vtgate as a server, and example files for starting vtgate as well as the mysql command-line application.
[vtgate_with_ssl.zip](https://github.com/vitessio/website/files/4507270/vtgate_with_ssl.zip)

**Comment by J0** [comment]
Hey @chrisrgithub,

Hope all is still well over at Mountain View. Could I take this issue?

Joel

**Comment by hallaroo** [comment]
This should now be covered by: https://vitess.io/docs/user-guides/configuration-advanced/transport-security-model/
