### ISSUE TITLE
UI toggle between helm and local installation features

### ISSUE THREAD

**Issue by morgo** [vitessio/website#440]
These two guides are new to Vitess 6:
* https://vitess.io/docs/user-guides/move-tables/
* https://vitess.io/docs/user-guides/resharding/

Note that they are the same guide for a Helm installation as a local installation (which is a nice improvement over the previous guides, and makes maintenance easier).

However, in MoveTables there is 1 example specific to Helm and in Resharding there are 3 examples.

Is it possible to have a UI toggle so a user can see "helm" by default, but then switch to see "local"? This would make it easier on readers.

**Comment by deepthi** [comment]
We now have 3 variants: Operator, local installation and helm installation.

**Comment by celestehorgan** [comment]
@morgo Looking into this.

**Comment by celestehorgan** [comment]
@morgo to be clear:

We're talking specifically about these four sections:

-  https://vitess.io/docs/user-guides/move-tables/#create-new-tablets 
- https://vitess.io/docs/user-guides/resharding/#apply-vschema
- https://vitess.io/docs/user-guides/resharding/#create-new-shards
- https://vitess.io/docs/user-guides/resharding/#cleanup

Correct? 

The first way to implement this that comes to mind is using a tabbed-style interface for each of the topics above, [similar to Kubernetes.io](https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-using-native-package-management). 

One important thing to note is that this will remove those entries from the right-hand nav.

I think it's useful to keep those links in the nav, personally, so another way to implement this that I'd suggest is using a collapsible panel/card, similar in implementation to [this codepen example](https://codepen.io/brussell98/pen/mEwxjP). This will allow us to have headers external to the tabs (preserving the nav), and expand Helm by default. 

Thoughts? :)


Edit: Also, when possible please unassign @lucperkins, who's recently left the LF taken on his first role as a developer!! 🎉 🎉 🎉  We're excited for him but it's time to stop clogging up his GH with LF-related issues!!

**Comment by deepthi** [comment]
I like the tabs on the kubernetes tutorial. I think it's fine to not have the subsections on the right nav.
Please note that we have deprecated the helm example, so the order should be:
1. Operator
2. Local
3. Helm

**Comment by celestehorgan** [comment]
@deepthi Sounds good! I'll get on it :D

**Comment by deepthi** [comment]
The changes in #487 broke the search functionality on the website, I so reverted them in #494. They will need to be re-done in a way that doesn't produce this error.
![vitess_io_error](https://user-images.githubusercontent.com/388311/91217418-527f1b00-e6cc-11ea-937b-4f7534b95b9d.png)

**Comment by hallaroo** [comment]
Helm has been deleted, so closing this out.
