### ISSUE TITLE
Document command line options

### ISSUE THREAD

**Issue by deepthi** [vitessio/website#445]
The following vitess modules probably each need their own page of options:
- vttablet. As we move to yaml config, we need to document that as well.
- vtgate
- vtctld
- vtworker (until it is deprecated)

Others?

**Comment by morgo** [comment]
Thanks @deepthi - we can document these when we get to "Programs" in reference refactoring https://github.com/vitessio/website/issues/331

**Comment by derekperkins** [comment]
It'll be awesome to finally know which flags actually work on which binary

**Comment by hallaroo** [comment]
I think these have been broken out here:
https://vitess.io/docs/reference/programs/vttablet/
https://vitess.io/docs/reference/programs/vtgate/ 
https://vitess.io/docs/reference/programs/vtctld/ 
https://vitess.io/docs/reference/programs/vtexplain/
