### ISSUE TITLE
dropdown menu items are off-screen in non-full-screen window

### ISSUE THREAD

**Issue by deepthi** [vitessio/website#471]
Ubuntu 18.04, Chrome Version 84.0.4147.89 (Official Build) (64-bit)

Dropdown menu items are not visible, see screenshot.

![dropdown](https://user-images.githubusercontent.com/388311/87875747-3dee8b00-c988-11ea-94c3-7e846121fb70.png)

**Comment by zacharysarah** [comment]
MacOS 10.15.5, Chrome 84.0.4147.89

![Screen Shot 2020-07-20 at 5 18 30 PM](https://user-images.githubusercontent.com/3210446/87998543-15ac7c80-caad-11ea-929f-db4fa7f3d808.png)

**Comment by deepthi** [comment]
It shows up like :point_up_2: when I do fullscreen (or use a bigger monitor). It's only when the window is smaller that it changes to the other layout.

**Comment by chalin** [comment]
@deepthi - I can reproduce the problem. Was this ever working properly at some point?

**Comment by deepthi** [comment]
> @deepthi - I can reproduce the problem. Was this ever working properly at some point?

I don't know. I have seen it happening for a while now, but only now got around to filing an issue.
