### ISSUE TITLE
Versioned docs

### ISSUE THREAD

**Issue by deepthi** [vitessio/website#473]
It will be nice to start publishing some of the documentation by major release version.
[Program reference](https://vitess.io/docs/reference/programs/) is an obvious section for versioning.
There might be others.

Cc @aquarapid @lkburns

**Comment by gedgar** [comment]
On a related note, it would be nice if our upgrade docs had a link to a page dedicated to incompatible changes between releases.

**Comment by hallaroo** [comment]
We have versioned PDFs on the site now. Closing out.

**Comment by deepthi** [comment]
We have something better now, see #907 🎉
