### ISSUE TITLE
Improve Vindex Documentation

### ISSUE THREAD

**Issue by gedgar** [vitessio/website#474]
- ~Document all available vindex types (add docs for multi-column vindexes, add any unlisted vindexes (eg `xxhash`), etc)~
- ~Improve Predefined Vindexes table (add column for supported ~column~ data types)~
- ~Fix 'iNdentity' typo~ Fixed in https://github.com/vitessio/website/pull/475

**Comment by aquarapid** [comment]
First pass merged in https://github.com/vitessio/website/pull/485

Only major outstanding item is examples and/or pointers to examples.

**Comment by hallaroo** [comment]
Closing this one out due to work @gedgar did
