### ISSUE TITLE
Auto-generator not displaying description of command line parameters 

### ISSUE THREAD

**Issue by hallaroo** [vitessio/website#498]
In the Vitess documentation for [vtctl Keyspace Command Reference ](https://vitess.io/docs/reference/programs/vtctl/keyspaces/#validatekeyspace) the command line parameters from the [vtctl.go](https://github.com/vitessio/vitess/blob/master/go/vt/vtctl/vtctl.go#L24) documentation are displayed. However, the subsequent descriptions from the same documentation are not.

Can we investigate to determine why this is occurring and get that information added back in? Thanks!

**Comment by aquarapid** [comment]
Seems like this is by design;  at some point this was auto-generated, but that stopped.  We should manually migrate descriptions where they are missing to the docs, and then add on to that in the docs, instead of having to add the detail to the code.
