### ISSUE TITLE
website should have og:image set

### ISSUE THREAD

**Issue by deepthi** [vitessio/website#534]
When I try to embed a link to a vitess website page in some other site (like LinkedIn), I would like it to show an image on the link. Right now there is none and it looks like this:
![linkedin-embed](https://user-images.githubusercontent.com/388311/94604238-3a129b00-024c-11eb-81a6-06fac5c164b0.png)

What I found out is that the website code needs to set og:image, though I don't know exactly where we would fix this.
While we are at it, we should also validate og:title.

**Comment by askdba** [comment]
@nate-double-u can I have your attention on this as well? We have a long awaiting ticket on this https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-553 
Thanks,

**Comment by doeg** [comment]
👋 I'm happy to give this one a go over the weekend!

**Comment by deepthi** [comment]
>  I'm happy to give this one a go over the weekend!

Sounds wonderful!
