### ISSUE TITLE
Update resources

### ISSUE THREAD

**Issue by deepthi** [vitessio/website#566]
https://vitess.io/docs/resources/presentations/

The links for Kubecon NA 2019 (San Diego) should be updated to point to the youtube videos.
We need a section for Kubecon Virtual EU 2020 with links to youtube recordings.

We should also post a link to the recording of Sugu's orchestrator webinar.
And anything else you can think of :)

**Comment by askdba** [comment]
Done https://github.com/vitessio/website/pull/730
