### ISSUE TITLE
Consolidate and update schema deployment user guides

### ISSUE THREAD

**Issue by sougou** [vitessio/website#652]
There are currently two different pages/sections for schema deployment:
* https://vitess.io/docs/user-guides/operating-vitess/making-schema-changes/
* https://vitess.io/docs/user-guides/schema-changes/

We should merge the two and update them to also talk about the new features we've added.

**Comment by sougou** [comment]
Looks like that last PR fixed this.

**Comment by shlomi-noach** [comment]
Seems to be solved by https://github.com/vitessio/website/pull/653
