### ISSUE TITLE
vschema user guide doc request

### ISSUE THREAD

**Issue by sougou** [vitessio/website#680]
From @jmoldow:

Can you also discuss the relationship between backups and the recommended max/min/avg/median shard sizes?

Could you possibly also discuss the pros/cons between manually maintaining your keyspace id partitionings, vs. doing an even power-of-2 partitioning? And the kind of scenarios where the former would be required (region sharding, poorly-chosen sharding key with hotspots, etc.)

**Comment by hallaroo** [comment]
This was mostly addressed by adding: https://vitess.io/docs/user-guides/vschema-guide/

A short note about shard sizes and backups is going to be added to the rule of thumb section here: https://github.com/vitessio/website/pull/897
