### ISSUE TITLE
cover various pools

### ISSUE THREAD

**Issue by sougou** [vitessio/website#681]
From @jmoldow:

It might also be useful to have a page or a section dedicated to understanding the different kinds of pools that exist in VTGate and VTTablet.

**Comment by hallaroo** [comment]
Vttablet pools are documented [here](https://vitess.io/docs/reference/features/connection-pools/)

Might still need documentation on vgtate pools

**Comment by deepthi** [comment]
I don't think vtgate has any pools ???
cc @systay @harshit-gangal

**Comment by harshit-gangal** [comment]
VTGate does not have any connection pool

**Comment by hallaroo** [comment]
Awesome! Then this should be all fixed and I'll close this out. Thank you both!
