### ISSUE TITLE
change the vttablet setting 

### ISSUE THREAD

**Issue by happi-lee** [vitessio/website#691]
I'd like to change vttablet's Args --queryserver-config-max-result-size 10000 to 1000000.
But I can't because of the error below. 

$ vttablet -tablet-path zone1-1553962377 -tablet_dir=/vt/vtdataroot/vt_1553962377 --queryserver-config-max-result-size=1000000
F0128 02:28:42.891954    3306 vttablet.go:152] mycnf read failed: open /vt/vt/vtdataroot/vt_1553962377/my.cnf: no such file or directory

How can I fix this?

**Comment by happi-lee** [comment]
vitess@example-vttablet-zone1-1553962377-f9ed137d:/vt/vtdataroot/vt_1553962377$ ls -lrt
total 36
drwxrwsr-x 2 vitess vitess 4096 Jan 25 09:07 relay-logs
drwxrwsr-x 4 vitess vitess 4096 Jan 25 09:07 innodb
-rw-rw-r-- 1 vitess vitess 2717 Jan 27 12:19 my.cnf.previous
-rw------- 1 vitess vitess 2704 Jan 27 12:19 my.cnf
drwxrwsr-x 8 vitess vitess 4096 Jan 27 12:19 data
drwxrwsr-x 2 vitess vitess 4096 Jan 27 12:19 tmp
-rw-rw---- 1 vitess vitess  537 Jan 27 12:19 slow-query.log
drwxrwsr-x 2 vitess vitess 4096 Jan 27 12:19 bin-logs
-rw-r----- 1 vitess vitess    4 Jan 27 12:19 mysql.pid

**Comment by happi-lee** [comment]
I configured this with  k8s operator (https://vitess.io/docs/get-started/operator/). 
I'm not get used to k8s environment.

**Comment by deepthi** [comment]
The documentation for `tablet_dir`:
```
The directory within the vtdataroot to store vttablet/mysql files. Defaults to being generated by the tablet uid.
```
It is relative to `$VTDATAROOT`. So please check the value of that env variable and set `-tablet_dir=<path relative to $VTDATAROOT>`.

**Comment by happi-lee** [comment]
Thank you for your help.
But The actual my.cnf file exists in $VTDATAROOT/vt_1553962377, not $VTDATAROOT. 
So, when I entered the command below, 
following message is : 

1) ubuntu@ip-172-31-18-149:~/environment/metrics-server$ vttablet -tablet-path zone1-1553962377 -tablet_dir=$vtdataroot --queryserver-config-max-result-size=1000000
F0128 04:43:49.544924    5433 vttablet.go:152] mycnf read failed: open /vt/vt_1553962377/my.cnf: no such file or directory
2) ubuntu@ip-172-31-18-149:~/environment/metrics-server$ vttablet -tablet-path zone1-1553962377  --queryserver-config-max-result-size=1000000
F0128 04:43:59.330461    5444 vttablet.go:152] mycnf read failed: open /vt/vt_1553962377/my.cnf: no such file or directory
3) ubuntu@ip-172-31-18-149:~/environment/metrics-server$ vttablet -tablet-path zone1-1553962377 -tablet_dir=/vt/vtdataroot/ --queryserver-config-max-result-size=1000000
F0128 04:44:15.668380    5455 vttablet.go:152] mycnf read failed: open /vt/vt/vtdataroot/my.cnf: no such file or directory

**Comment by deepthi** [comment]
Whatever you are passing as `-tablet_dir` needs to match where the files are.
I'm wondering why you even need to pass this parameter. All our examples default it.
I suggest you start again from the beginning and try restarting vttablet without passing this parameter.

Other option is that with the operator you can pass `extraFlags`.
Add your `queryserver-config` flag to that section in `101_initial_cluster.yaml` and tablets will come up with the flag already set.

**Comment by happi-lee** [comment]
I'd like to change that parameter because I am conducting a stress test using Vitess. 
To measure the execute speed and CPU/IO by putting 1 million data each sharded/nonsharded keyspaces and execute the Select All query.  But with the default parameter of --queryserver-config-max-result-size, I can't list all data of my keyspaces. 

Add your queryserver-config flag to that section in 101_initial_cluster.yaml 
: is that right with this?? 

**101_initial_cluster.yaml** 
keyspaces: 
- name : commerce 
.
.
.
            vttablet:
              extraFlags:
                db_charset: utf8mb4
                **type : integer
                queryserver-config-max-result-size: 1000000**

**Comment by deepthi** [comment]
You don't need the `type:integer` line
Put the number in quotes:
```
vttablet:
  extraFlags:
    db_charset: utf8mb4
    queryserver-config-max-result-size: "1000000"
```
Please note that the memory required by your vttablets and vtgate is going to be higher by overriding this.
Also that OLTP applications should not be fetching such large numbers of rows.

**Comment by happi-lee** [comment]
Oh It worked by setting as you advised me and successfully changed the value. I really appreciate for your help. 
And I noticed that in Real Application i don't need such setting, it's just limited to load test.
