### ISSUE TITLE
Better Document Reshard Options/defaults

### ISSUE THREAD

**Issue by Anders-PlanetScale** [vitessio/website#707]
We had a user run into issues in attempting to run a reshard workflow where adding the option -tablet_type=MASTER was required in order to run the reshard (This users DB resides on Aurora and only the Master is able to have binary logs enabled). 

Lack of documentation of reshard options and defaults meant the customer was not aware that they could pass a -tablet_type option to reshard and they were not aware that the option defaulted to REPLICA,READPNLY.

We should try to better define the default options for reshard and/or add descriptions of all the options you can pass to the workflow in the documentation.

**Comment by hallaroo** [comment]
Notes: We'd want to adjust this page: https://vitess.io/docs/reference/vreplication/reshard/
