### ISSUE TITLE
Update the mysqldump section to reflect additional variables

### ISSUE THREAD

**Issue by hallaroo** [vitessio/website#742]
Page: https://vitess.io/docs/user-guides/configuration-basic/exporting-data/ 
Section: https://vitess.io/docs/user-guides/configuration-basic/exporting-data/#mysqldump

Areas to fix:

- Additional variables need to be added to the above page. We need to point to mysqldump properly using host, port, username and password
- Remove the line containing the skip network timeout qualification on vitess 7.0 as that was fixed

**Comment by kristee-planetscale** [comment]
completed: 
- Remove the line containing the skip network timeout qualification on vitess 7.0 as that was fixed

see merged PR: https://github.com/vitessio/website/pull/965 (updated 11.0, 12.0, 13.0 and 14.0 docs)

pending response before adding the following: 
- Additional variables need to be added to the above page. We need to point to mysqldump properly using host, port, username and password

**Comment by aquarapid** [comment]
We can change it to something like:

```
$ mysqldump  --set-gtid-purged=OFF --no-tablespaces .... commerce > commerce.sql
```

and then under the options bullets add:

 * `....`:  Additional mysqldump options like:  `-u <user>`, `-p <password>`, `-h <database server hostname>`

**Comment by kristee-planetscale** [comment]
PR Merged: https://github.com/vitessio/website/pull/967
