### ISSUE TITLE
Incorrectly working redirects

### ISSUE THREAD

**Issue by nate-double-u** [vitessio/website#917]
Follow up to #912

file: `layouts/index.redirects`

## Incorrectly working redirects

I'm not sure that these worked before #912. How are these supposed to work?

```
/vitess/*   go-get=1 /go-import/vitess.html   200
/messages/* go-get=1 /go-import/messages.html 200
/operator/* go-get=1 /go-import/operator.html 200
```

For example: https://vitess.io/vitess/vitess.html 404s, but https://vitess.io/go-import/vitess.html (the redirect target) does load (albeit a blank page with some headers set).

_Originally posted by @nate-double-u in https://github.com/vitessio/website/issues/912#issuecomment-998339354_

**Comment by derekperkins** [comment]
Those redirects appear to still be working fine. They are specifically there to handle our Go vanity import - `go get vitess.io/vitess`

**Comment by nate-double-u** [comment]
I'm happy to hear that @derekperkins!

Can I ask what the test is for them? I don't know the context of their use.

**Comment by nate-double-u** [comment]
I'm glad to hear that @derekperkins! Thanks for checking 🙂

**Comment by derekperkins** [comment]
You have to have Go installed, then you can run:
- `go get vitess.io/vitess`
- `go get vitess.io/operator`
- `go get vitess.io/messages`

If that completes successfully, the redirects are working
